# Predicction module using truncated SVD

### Read cvs

In [1]:
import numpy as np
import pandas as pnd

In [6]:
dataset = pnd.read_csv("../data/user_song_ratings_transformed_final.csv", index_col=0)
dataset

C:\Users\eltaq\AppData\Roaming\Python\Python39\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


user_id             song_id  \
0   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   
..                                       ...                 ...   
20                                        22          iYbIz9xWPk   
21                                        22          hLhKqL6v9k   
22                                        22          8XIue34ELi   
23                                        22          XQbxmZpjDr   
41                                        22          pZZWtRZgwY   

    listen_count  ratings  bd_ids  
0              1      1.0   39526  
1              2      1.0   39527  
2              1      1.0      21  
3              1      1.0   39528  
4              1      1.0     364  
..           ...      ...     ...  
20            20      5.0   29333  
21            20      5.0   16648  
22            20      5.0   10875  
23            20      5.0    6502  
41            16      4.0   33849  

[1392704 rows x 5 columns]

### Change all the ratings on 0 to 1 (this happend bc the rating method used)

In [7]:
dataset['ratings'].value_counts()

0.0    479233
1.0    472840
2.0    252114
5.0    101373
3.0     52562
4.0     34582
Name: ratings, dtype: int64

In [8]:
pre_processed_dataset = dataset.replace({0: 1})
pre_processed_dataset['ratings'].value_counts()


1.0    952073
2.0    252114
5.0    101373
3.0     52562
4.0     34582
Name: ratings, dtype: int64

In [9]:
processed_dataset = pre_processed_dataset.drop(["listen_count", "song_id"], axis=1)
processed_dataset.sort_values('bd_ids', inplace=True)
processed_dataset.reset_index(inplace=True, drop=True)
processed_dataset

user_id  ratings  bd_ids
0                                              18      1.0       1
1                                              18      1.0       2
2                                              18      1.0       3
3        d53998d808f272e4d38767b7b73efa540291e640      5.0       5
4        d99cce8777bc1c18bf543498b23f7fc04f4e5fac      1.0       5
...                                           ...      ...     ...
1392699  5a72dca4bbab6a28fbf40a7dcf12d098b7f6ac16      2.0   44840
1392700  e8a2d794466a3902fd98770281b7b2bc582b16b6      1.0   44840
1392701  53f48e284f09ca172a1c3fa9fb649103a048e1b7      5.0   44840
1392702  3aff7dd207c5f587c45c653947181d3ee12a2201      1.0   44840
1392703  7c8f7259cc349d3dca9f6003434d70e1ecf51654      1.0   44840

[1392704 rows x 3 columns]

In [10]:
pivot_table = pnd.pivot_table(processed_dataset, values='ratings', index='bd_ids', columns='user_id')

In [11]:
print(np.round(processed_dataset[processed_dataset['bd_ids'] == 5]['ratings'].mean()))

2.0


In [12]:
pivot_table

user_id  00003a4459f33b92906be11abe0e93efc423c0ff  \
bd_ids                                              
1                                             NaN   
2                                             NaN   
3                                             NaN   
5                                             NaN   
8                                             NaN   
...                                           ...   
44836                                         NaN   
44837                                         NaN   
44838                                         NaN   
44839                                         NaN   
44840                                         NaN   

user_id  00005c6177188f12fb5e2e82cdbd93e8a3f35e64  \
bd_ids                                              
1                                             NaN   
2                                             NaN   
3                                             NaN   
5                                             NaN   
8                                             NaN   
...                                           ...   
44836                                         NaN   
44837                                         NaN   
44838                                         NaN   
44839                                         NaN   
44840                                         NaN   

user_id  00030033e3a2f904a48ec1dd53019c9969b6ef1f  \
bd_ids                                              
1                                             NaN   
2                                             NaN   
3                                             NaN   
5                                             NaN   
8                                             NaN   
...                                           ...   
44836                                         NaN   
44837                                         NaN   
44838                                         NaN   
44839                                         NaN   
44840                                         NaN   

user_id  0007235c769e610e3d339a17818a5708e41008d9  \
bd_ids                                              
1                                             NaN   
2                                             NaN   
3                                             NaN   
5                                             NaN   
8                                             NaN   
...                                           ...   
44836                                         NaN   
44837                                         NaN   
44838                                         NaN   
44839                                         NaN   
44840                                         NaN   

user_id  0007c0e74728ca9ef0fe4eb7f75732e8026a278b  \
bd_ids                                              
1                                             NaN   
2                                             NaN   
3                                             NaN   
5                                             NaN   
8                                             NaN   
...                                           ...   
44836                                         NaN   
44837                                         NaN   
44838                                         NaN   
44839                                         NaN   
44840                                         NaN   

user_id  000a5c8b4d8b2c98f7a205219181d039edcd4506  \
bd_ids                                              
1                                             NaN   
2                                             NaN   
3                                             NaN   
5                                             NaN   
8                                             NaN   
...                                           ...   
44836                                         NaN   
44837                                         NaN   
44838               

In [13]:
np.round(pivot_table.mean(axis=1))

bd_ids
1        1.0
2        1.0
3        1.0
5        2.0
8        1.0
        ... 
44836    2.0
44837    2.0
44838    2.0
44839    2.0
44840    2.0
Length: 6901, dtype: float64

In [14]:
back_up = pivot_table

In [15]:
back_up = back_up.where(pivot_table.notna(), np.round(pivot_table.mean(axis=1)), axis=0)

In [16]:
back_up

user_id  00003a4459f33b92906be11abe0e93efc423c0ff  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  00005c6177188f12fb5e2e82cdbd93e8a3f35e64  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  00030033e3a2f904a48ec1dd53019c9969b6ef1f  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  0007235c769e610e3d339a17818a5708e41008d9  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  0007c0e74728ca9ef0fe4eb7f75732e8026a278b  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  000a5c8b4d8b2c98f7a205219181d039edcd4506  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838               

In [17]:
back_up.sort_values('bd_ids', inplace=True)


In [18]:
back_up

user_id  00003a4459f33b92906be11abe0e93efc423c0ff  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  00005c6177188f12fb5e2e82cdbd93e8a3f35e64  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  00030033e3a2f904a48ec1dd53019c9969b6ef1f  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  0007235c769e610e3d339a17818a5708e41008d9  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  0007c0e74728ca9ef0fe4eb7f75732e8026a278b  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838                                         2.0   
44839                                         2.0   
44840                                         2.0   

user_id  000a5c8b4d8b2c98f7a205219181d039edcd4506  \
bd_ids                                              
1                                             1.0   
2                                             1.0   
3                                             1.0   
5                                             2.0   
8                                             1.0   
...                                           ...   
44836                                         2.0   
44837                                         2.0   
44838               

In [19]:
valid_songs = processed_dataset['bd_ids'].unique()
valid_songs.sort()

In [20]:
valid_songs

array([    1,     2,     3, ..., 44838, 44839, 44840], dtype=int64)

In [21]:
np_matrix = back_up.sort_values('bd_ids').to_numpy()

In [22]:
np_matrix.shape

(6901, 75760)

In [23]:
np_matrix

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]])

In [24]:
print(f"{np_matrix.shape[0]} x {np_matrix.shape[1]} our pivot table")

6901 x 75760 our pivot table


In [25]:
print(np_matrix[:, :].T.shape)

(75760, 6901)


## Truncated SVD with Sklearn

In [26]:
from sklearn.decomposition import TruncatedSVD

In [27]:
train_data = np_matrix[:, :]
# test_data = np_matrix[8000:, :]

In [28]:
train_data.shape

(6901, 75760)

In [29]:
song_svd = TruncatedSVD(n_components=50)

In [30]:
song_features = song_svd.fit_transform(train_data.T) # U * Sigma

In [31]:
song_features

array([[ 1.49053569e+02,  1.02846752e-01, -2.00451969e-02, ...,
        -4.83982497e-04, -1.88680971e-02,  1.48311803e-02],
       [ 1.49060353e+02,  8.08336608e-02, -2.63831855e-02, ...,
        -1.16030795e-03, -8.04753497e-03, -1.39955465e-03],
       [ 1.49066747e+02,  9.80777277e-01, -9.93861002e-02, ...,
        -1.72714155e-02,  3.13755289e-02, -1.98479693e-02],
       ...,
       [ 1.49080533e+02,  7.95562667e-02, -2.48002087e-02, ...,
        -9.98782871e-03,  8.37071151e-04, -2.30106411e-03],
       [ 1.49093860e+02, -3.97428146e-04, -4.92235906e-01, ...,
         2.38591279e-02, -5.93468064e-03, -1.46444999e-02],
       [ 1.49738094e+02,  2.77290257e-01, -2.11208924e-02, ...,
        -6.87205341e-02,  9.47380266e-01, -2.76910783e-01]])

In [32]:
song_features.shape

(75760, 50)

In [33]:
v_T = song_svd.components_.T # vT

In [34]:
v_T.shape

(6901, 50)

In [35]:
sigma = np.diag(song_svd.singular_values_)
sigma

array([[41002.99159122,     0.        ,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [    0.        ,   147.06233604,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,   139.92641368, ...,
            0.        ,     0.        ,     0.        ],
       ...,
       [    0.        ,     0.        ,     0.        , ...,
           49.69646995,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        , ...,
            0.        ,    49.22021943,     0.        ],
       [    0.        ,     0.        ,     0.        , ...,
            0.        ,     0.        ,    49.18434563]])

In [36]:
v_T.shape

(6901, 50)

#### Calculate distance matrix with scipy

In [37]:
from scipy.spatial import distance_matrix

In [38]:
v_T

array([[ 6.71280445e-03, -1.44711847e-03, -2.36622450e-04, ...,
        -5.26982319e-05,  1.06403175e-04,  5.89651584e-04],
       [ 6.71280445e-03, -1.44711847e-03, -2.36622450e-04, ...,
        -5.26982319e-05,  1.06403175e-04,  5.89651584e-04],
       [ 6.71280445e-03, -1.44711847e-03, -2.36622450e-04, ...,
        -5.26982319e-05,  1.06403175e-04,  5.89651584e-04],
       ...,
       [ 1.34232306e-02, -2.27684748e-03, -2.61050765e-04, ...,
        -9.64701728e-05,  8.61560980e-05, -1.71867984e-03],
       [ 1.34239311e-02, -2.47758126e-03, -3.29801265e-04, ...,
         6.08603314e-04,  5.86832922e-04, -2.56710574e-04],
       [ 1.34232260e-02, -2.49206447e-03, -6.20910034e-04, ...,
         5.51232557e-04, -1.79467446e-04,  1.32215545e-03]])

In [39]:
diagonal_distance_matrix = distance_matrix(v_T[:, :], v_T[:, :])

In [40]:
diagonal_distance_matrix

array([[0.00000000e+00, 9.05291982e-16, 8.59024732e-16, ...,
        8.33888469e-03, 8.82836283e-03, 7.94564277e-03],
       [9.05291982e-16, 0.00000000e+00, 1.09596667e-15, ...,
        8.33888469e-03, 8.82836283e-03, 7.94564277e-03],
       [8.59024732e-16, 1.09596667e-15, 0.00000000e+00, ...,
        8.33888469e-03, 8.82836283e-03, 7.94564277e-03],
       ...,
       [8.33888469e-03, 8.33888469e-03, 8.33888469e-03, ...,
        0.00000000e+00, 6.58501699e-03, 6.84661955e-03],
       [8.82836283e-03, 8.82836283e-03, 8.82836283e-03, ...,
        6.58501699e-03, 0.00000000e+00, 6.16332535e-03],
       [7.94564277e-03, 7.94564277e-03, 7.94564277e-03, ...,
        6.84661955e-03, 6.16332535e-03, 0.00000000e+00]])

In [41]:
dump_test = pnd.DataFrame(data=diagonal_distance_matrix, columns=[item for item in valid_songs.astype(str)], index=valid_songs)

In [42]:
dump_test

1             2             3         5         8  \
1      0.000000e+00  9.052920e-16  8.590247e-16  0.832946  0.423635   
2      9.052920e-16  0.000000e+00  1.095967e-15  0.832946  0.423635   
3      8.590247e-16  1.095967e-15  0.000000e+00  0.832946  0.423635   
5      8.329462e-01  8.329462e-01  8.329462e-01  0.000000  0.550751   
8      4.236352e-01  4.236352e-01  4.236352e-01  0.550751  0.000000   
...             ...           ...           ...       ...       ...   
44836  9.072701e-03  9.072701e-03  9.072701e-03  0.834227  0.424528   
44837  8.018601e-03  8.018601e-03  8.018601e-03  0.832695  0.423608   
44838  8.338885e-03  8.338885e-03  8.338885e-03  0.833182  0.423537   
44839  8.828363e-03  8.828363e-03  8.828363e-03  0.834968  0.425881   
44840  7.945643e-03  7.945643e-03  7.945643e-03  0.832866  0.423525   

                 15            16            17        21            25  ...  \
1      7.207700e-16  5.607360e-16  8.169232e-16  0.196929  5.363770e-16  ...   
2      1.094142e-15  9.157739e-16  1.099210e-15  0.196929  8.923159e-16  ...   
3      1.020727e-15  9.155799e-16  1.081551e-15  0.196929  8.949526e-16  ...   
5      8.329462e-01  8.329462e-01  8.329462e-01  0.865276  8.329462e-01  ...   
8      4.236352e-01  4.236352e-01  4.236352e-01  0.472580  4.236352e-01  ...   
...             ...           ...           ...       ...           ...  ...   
44836  9.072701e-03  9.072701e-03  9.072701e-03  0.196744  9.072701e-03  ...   
44837  8.018601e-03  8.018601e-03  8.018601e-03  0.196932  8.018601e-03  ...   
44838  8.338885e-03  8.338885e-03  8.338885e-03  0.197836  8.338885e-03  ...   
44839  8.828363e-03  8.828363e-03  8.828363e-03  0.196678  8.828363e-03  ...   
44840  7.945643e-03  7.945643e-03  7.945643e-03  0.197985  7.945643e-03  ...   

          44831     44832     44833     44834     44835     44836     44837  \
1      0.004630  0.007632  0.008104  0.007861  0.008070  0.009073  0.008019   
2      0.004630  0.007632  0.008104  0.007861  0.008070  0.009073  0.008019   
3      0.004630  0.007632  0.008104  0.007861  0.008070  0.009073  0.008019   
5      0.833365  0.833213  0.833365  0.833191  0.832721  0.834227  0.832695   
8      0.424016  0.423803  0.424422  0.424514  0.423385  0.424528  0.423608   
...         ...       ...       ...       ...       ...       ...       ...   
44836  0.010687  0.005500  0.007165  0.006538  0.006599  0.000000  0.006457   
44837  0.009112  0.005367  0.006947  0.005632  0.006269  0.006457  0.000000   
44838  0.010149  0.006020  0.005987  0.006492  0.007009  0.007271  0.006405   
44839  0.010273  0.006880  0.007038  0.005429  0.007560  0.007192  0.006610   
44840  0.009016  0.004073  0.006138  0.005001  0.005155  0.005328  0.005441   

          44838     44839     44840  
1      0.008339  0.008828  0.007946  
2      0.008339  0.008828  0.007946  
3      0.008339  0.008828  0.007946  
5      0.833182  0.834968  0.832866  
8      0.423537  0.425881  0.423525  
...         ...       ...       ...  
44836  0.007271  0.007192  0.005328  
44837  0.006405  0.006610  0.005441  
44838  0.000000  0.006585  0.006847  
44839  0.006585  0.000000  0.006163  
44840  0.006847  0.006163  0.000000  

[6901 rows x 6901 columns]

In [43]:
dump_test['5'].sort_values(ascending=True).index[1:6]

Int64Index([8, 40191, 40008, 40197, 40932], dtype='int64')

In [44]:
dump_test = dump_test.reset_index()

In [45]:
dump_test

index             1             2             3         5         8  \
0         1  0.000000e+00  9.052920e-16  8.590247e-16  0.832946  0.423635   
1         2  9.052920e-16  0.000000e+00  1.095967e-15  0.832946  0.423635   
2         3  8.590247e-16  1.095967e-15  0.000000e+00  0.832946  0.423635   
3         5  8.329462e-01  8.329462e-01  8.329462e-01  0.000000  0.550751   
4         8  4.236352e-01  4.236352e-01  4.236352e-01  0.550751  0.000000   
...     ...           ...           ...           ...       ...       ...   
6896  44836  9.072701e-03  9.072701e-03  9.072701e-03  0.834227  0.424528   
6897  44837  8.018601e-03  8.018601e-03  8.018601e-03  0.832695  0.423608   
6898  44838  8.338885e-03  8.338885e-03  8.338885e-03  0.833182  0.423537   
6899  44839  8.828363e-03  8.828363e-03  8.828363e-03  0.834968  0.425881   
6900  44840  7.945643e-03  7.945643e-03  7.945643e-03  0.832866  0.423525   

                15            16            17        21  ...     44831  \
0     7.207700e-16  5.607360e-16  8.169232e-16  0.196929  ...  0.004630   
1     1.094142e-15  9.157739e-16  1.099210e-15  0.196929  ...  0.004630   
2     1.020727e-15  9.155799e-16  1.081551e-15  0.196929  ...  0.004630   
3     8.329462e-01  8.329462e-01  8.329462e-01  0.865276  ...  0.833365   
4     4.236352e-01  4.236352e-01  4.236352e-01  0.472580  ...  0.424016   
...            ...           ...           ...       ...  ...       ...   
6896  9.072701e-03  9.072701e-03  9.072701e-03  0.196744  ...  0.010687   
6897  8.018601e-03  8.018601e-03  8.018601e-03  0.196932  ...  0.009112   
6898  8.338885e-03  8.338885e-03  8.338885e-03  0.197836  ...  0.010149   
6899  8.828363e-03  8.828363e-03  8.828363e-03  0.196678  ...  0.010273   
6900  7.945643e-03  7.945643e-03  7.945643e-03  0.197985  ...  0.009016   

         44832     44833     44834     44835     44836     44837     44838  \
0     0.007632  0.008104  0.007861  0.008070  0.009073  0.008019  0.008339   
1     0.007632  0.008104  0.007861  0.008070  0.009073  0.008019  0.008339   
2     0.007632  0.008104  0.007861  0.008070  0.009073  0.008019  0.008339   
3     0.833213  0.833365  0.833191  0.832721  0.834227  0.832695  0.833182   
4     0.423803  0.424422  0.424514  0.423385  0.424528  0.423608  0.423537   
...        ...       ...       ...       ...       ...       ...       ...   
6896  0.005500  0.007165  0.006538  0.006599  0.000000  0.006457  0.007271   
6897  0.005367  0.006947  0.005632  0.006269  0.006457  0.000000  0.006405   
6898  0.006020  0.005987  0.006492  0.007009  0.007271  0.006405  0.000000   
6899  0.006880  0.007038  0.005429  0.007560  0.007192  0.006610  0.006585   
6900  0.004073  0.006138  0.005001  0.005155  0.005328  0.005441  0.006847   

         44839     44840  
0     0.008828  0.007946  
1     0.008828  0.007946  
2     0.008828  0.007946  
3     0.834968  0.832866  
4     0.425881  0.423525  
...        ...       ...  
6896  0.007192  0.005328  
6897  0.006610  0.005441  
6898  0.006585  0.006847  
6899  0.000000  0.006163  
6900  0.006163  0.000000  

[6901 rows x 6902 columns]

In [46]:
dump_test.to_csv('./recomendation_IA.csv', index=False)