# SVD using tensorFlow

In [1]:
import numpy as np
import pandas as pnd
import tensorflow as tf

In [2]:
def cosine_similarity(a, b):
    '''
    This function will calculate the cosine similarity between two vectors
    '''
    return np.dot(a, b)/(np.linalg.norm(a)*np.linalg.norm(b))


In [3]:
dataset = pnd.read_csv("user_song_ratings.csv", index_col=0)
dataset

C:\Users\eltaq\AppData\Roaming\Python\Python39\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


user_id             song_id  \
0        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4        b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   
...                                           ...                 ...   
1999995  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJEYPO12AAA8C6B0E   
1999996  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJJYDE12AF729FC16   
1999997  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJKQSF12A6D4F5EE9   
1999998  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJUXGA12AC961885C   
1999999  d8bfd4ec88f0f3773a9e022e3c1a0f1d3b7b6a92  SOJYOLS12A8C13C06F   

         listen_count  ratings  
0                   1      1.0  
1                   2      1.0  
2                   1      1.0  
3                   1      1.0  
4                   1      1.0  
...               ...      ...  
1999995             2      1.0  
1999996             4      2.0  
1999997             3      2.0  
1999998             1      1.0  
1999999             1      1.0  

[2000000 rows x 4 columns]

In [4]:
pre_processed_dataset = dataset.replace({0: 1})

In [5]:
processed_dataset = pre_processed_dataset.drop(["listen_count"], axis=1)
processed_dataset.sort_values('song_id', inplace=True)
processed_dataset

user_id             song_id  ratings
639951   8fffc01119b0f79c95cad10b5827f9a60d19a68f  SOAAAGQ12A8C1420C8      1.0
848788   2c2a59d10d1c17b766567f0cde9955571545e710  SOAAAGQ12A8C1420C8      5.0
1507440  3192565c00ec4e9b91e90d5bce979c319a963721  SOAAAGQ12A8C1420C8      4.0
67468    43c6db7ff4608324722a10cc95bd1c5c69ab7952  SOAAAGQ12A8C1420C8      2.0
1097056  be82636cdaa522689141f43d3c97d807e8d34f30  SOAAAGQ12A8C1420C8      1.0
...                                           ...                 ...      ...
528187   959755a11438435823abfbfee55121c517405da8  SOZZZPV12A8C1444B5      1.0
386142   8ffc195c8df7f7280bc5e7a2707bb7689a0d646d  SOZZZPV12A8C1444B5      1.0
457540   35148bd25c2b2f9682d592de9314dd9f1da78b21  SOZZZPV12A8C1444B5      1.0
285180   3c0efcd44200a8a147e1c2a8f80438800bff4232  SOZZZPV12A8C1444B5      1.0
487645   53d60f8f3b3c47cd54f063925faee62105f9b6bb  SOZZZPV12A8C1444B5      1.0

[2000000 rows x 3 columns]

In [6]:
pivot_table = pnd.pivot_table(processed_dataset, values='ratings', index='song_id', columns='user_id')

In [7]:
back_up = pivot_table

In [8]:
back_up = back_up.where(pivot_table.notna(), np.round(pivot_table.mean(axis=1)), axis=0)

In [9]:
back_up

user_id             00003a4459f33b92906be11abe0e93efc423c0ff  \
song_id                                                        
SOAAAGQ12A8C1420C8                                       2.0   
SOAACPJ12A81C21360                                       2.0   
SOAACSG12AB018DC80                                       1.0   
SOAAEJI12AB0188AB5                                       1.0   
SOAAFAC12A67ADF7EB                                       1.0   
...                                                      ...   
SOZZTNF12A8C139916                                       1.0   
SOZZVWB12AB0189C30                                       1.0   
SOZZWZV12A67AE140F                                       2.0   
SOZZYAO12A6701FF36                                       2.0   
SOZZZPV12A8C1444B5                                       2.0   

user_id             00005c6177188f12fb5e2e82cdbd93e8a3f35e64  \
song_id                                                        
SOAAAGQ12A8C1420C8                                       2.0   
SOAACPJ12A81C21360                                       2.0   
SOAACSG12AB018DC80                                       1.0   
SOAAEJI12AB0188AB5                                       1.0   
SOAAFAC12A67ADF7EB                                       1.0   
...                                                      ...   
SOZZTNF12A8C139916                                       1.0   
SOZZVWB12AB0189C30                                       1.0   
SOZZWZV12A67AE140F                                       2.0   
SOZZYAO12A6701FF36                                       2.0   
SOZZZPV12A8C1444B5                                       2.0   

user_id             00030033e3a2f904a48ec1dd53019c9969b6ef1f  \
song_id                                                        
SOAAAGQ12A8C1420C8                                       2.0   
SOAACPJ12A81C21360                                       2.0   
SOAACSG12AB018DC80                                       1.0   
SOAAEJI12AB0188AB5                                       1.0   
SOAAFAC12A67ADF7EB                                       1.0   
...                                                      ...   
SOZZTNF12A8C139916                                       1.0   
SOZZVWB12AB0189C30                                       1.0   
SOZZWZV12A67AE140F                                       2.0   
SOZZYAO12A6701FF36                                       2.0   
SOZZZPV12A8C1444B5                                       2.0   

user_id             0007235c769e610e3d339a17818a5708e41008d9  \
song_id                                                        
SOAAAGQ12A8C1420C8                                       2.0   
SOAACPJ12A81C21360                                       2.0   
SOAACSG12AB018DC80                                       1.0   
SOAAEJI12AB0188AB5                                       1.0   
SOAAFAC12A67ADF7EB                                       1.0   
...                                                      ...   
SOZZTNF12A8C139916                                       1.0   
SOZZVWB12AB0189C30                                       1.0   
SOZZWZV12A67AE140F                                       2.0   
SOZZYAO12A6701FF36                                       2.0   
SOZZZPV12A8C1444B5                                       2.0   

user_id             0007c0e74728ca9ef0fe4eb7f75732e8026a278b  \
song_id                                                        
SOAAAGQ12A8C1420C8                                       2.0   
SOAACPJ12A81C21360                                       2.0   
SOAACSG12AB018DC80                                       1.0   
SOAAEJI12AB0188AB5                                       1.0   
SOAAFAC12A67ADF7EB                                       1.0   
...                                                      ...   
SOZZTNF12A8C139916                                       1.0   
SOZZVWB12AB0189C30                                       1.0   
SOZZWZV12A67AE140F          

In [10]:
np_matrix = back_up.sort_values('song_id').to_numpy()

In [11]:
print(np_matrix.T.shape)

(76353, 10000)


### Take np matrix to tensorFlow tensor

In [12]:
tf_tensor = tf.convert_to_tensor(np_matrix.T[:1000, :5000], dtype=tf.float32)

In [13]:
tf_tensor

<tf.Tensor: shape=(1000, 5000), dtype=float32, numpy=
array([[2., 2., 1., ..., 2., 2., 2.],
       [2., 2., 1., ..., 2., 2., 2.],
       [2., 2., 1., ..., 2., 2., 2.],
       ...,
       [2., 2., 1., ..., 2., 2., 2.],
       [2., 2., 1., ..., 2., 2., 2.],
       [2., 2., 1., ..., 2., 2., 2.]], dtype=float32)>

### Create the SVD

In [14]:
s, u, v = tf.linalg.svd(tf_tensor, full_matrices=True)

In [15]:
u

<tf.Tensor: shape=(1000, 1000), dtype=float32, numpy=
array([[-3.16346660e-02, -1.55498611e-03, -3.15168686e-03, ...,
         4.51171989e-09,  1.24577619e-08,  4.89089746e-09],
       [-3.16326246e-02, -1.45373319e-03, -2.93691340e-03, ...,
         1.25200387e-07,  9.93250353e-08, -2.31240254e-08],
       [-3.16264518e-02,  1.14366226e-03, -4.17298339e-02, ...,
         2.36096255e-07,  2.07826332e-07, -8.11463394e-08],
       ...,
       [-3.16286124e-02, -1.41804793e-03, -3.02794296e-03, ...,
         3.02916554e-08,  1.93903524e-08,  7.05747238e-09],
       [-3.16144824e-02, -5.41400071e-03, -2.91569773e-02, ...,
        -1.96272705e-08,  2.21415828e-08, -1.23845325e-08],
       [-3.16832773e-02, -3.39453062e-03, -3.35515221e-03, ...,
        -1.75980102e-08, -2.28425243e-08, -4.83494933e-09]], dtype=float32)>

### Truncate SVD to our components

In [16]:
num_components = 50

#### trucate U and V and Sigma

In [17]:
v.numpy().shape

(5000, 5000)

In [18]:
u_truncate = u[:, :num_components]
v_truncate = v[:num_components, :]
s_truncate = tf.linalg.diag(s)[:num_components, :num_components]
# u_truncate = u[:num_components, :]
# v_truncate = v[:num_components, :]
# s_truncate = tf.linalg.diag(s)[:num_components, :num_components]

In [19]:
u_truncate

<tf.Tensor: shape=(1000, 50), dtype=float32, numpy=
array([[-0.03163467, -0.00155499, -0.00315169, ...,  0.00018664,
         0.00182332,  0.00107973],
       [-0.03163262, -0.00145373, -0.00293691, ...,  0.00080232,
         0.00097478, -0.00108309],
       [-0.03162645,  0.00114366, -0.04172983, ...,  0.00448984,
        -0.00530337,  0.00459914],
       ...,
       [-0.03162861, -0.00141805, -0.00302794, ...,  0.00195195,
         0.00139525, -0.0003089 ],
       [-0.03161448, -0.005414  , -0.02915698, ...,  0.05111783,
         0.04657569,  0.04951353],
       [-0.03168328, -0.00339453, -0.00335515, ..., -0.00982353,
         0.00544944,  0.00022668]], dtype=float32)>

#### Calculate distance matrix with scipy

In [20]:
from scipy.spatial import distance_matrix

In [21]:
print(u_truncate.shape)
print(v_truncate.shape)

(1000, 50)
(50, 5000)


In [22]:
u_truncate_numpy = u_truncate.numpy()
v_truncate_numpy = v_truncate.numpy().T

In [23]:
diagonal_matrix_distance = distance_matrix(u_truncate_numpy, u_truncate_numpy)

In [24]:
diagonal_matrix_distance

array([[0.        , 0.01142305, 0.06879863, ..., 0.01420465, 0.14156425,
        0.07816217],
       [0.01142305, 0.        , 0.06785112, ..., 0.00593508, 0.14132837,
        0.07694291],
       [0.06879863, 0.06785112, 0.        , ..., 0.06854475, 0.161287  ,
        0.10324545],
       ...,
       [0.01420465, 0.00593508, 0.06854475, ..., 0.        , 0.13982872,
        0.07704651],
       [0.14156425, 0.14132837, 0.161287  , ..., 0.13982872, 0.        ,
        0.16831962],
       [0.07816217, 0.07694291, 0.10324545, ..., 0.07704651, 0.16831962,
        0.        ]])

In [29]:
diagonal_matrix_distance[1, :]

array([1.14230490e-02, 0.00000000e+00, 6.78511226e-02, 2.64624328e-04,
       2.64566057e-04, 9.80187887e-03, 2.81262075e-02, 9.09525612e-03,
       2.59085627e-03, 3.46168544e-01, 2.19923148e-01, 8.44927787e-02,
       4.18011105e-02, 1.85683331e-01, 1.42914094e-01, 2.70065343e-02,
       3.85083576e-03, 1.66965844e-01, 1.00157465e-01, 1.36635481e-01,
       5.19443583e-02, 1.89549296e-01, 4.67417558e-02, 2.53744502e-01,
       1.19981541e-03, 1.91682722e-01, 1.18840934e-01, 5.41912137e-02,
       4.30994224e-01, 8.70162591e-02, 2.46982432e-01, 3.05382313e-01,
       2.02184949e-01, 2.33500622e-01, 2.95398873e-01, 3.97167542e-01,
       4.56351496e-02, 5.42200453e-02, 4.97272666e-03, 1.13742918e-02,
       1.13143067e-02, 1.49727705e-03, 1.06597574e-01, 4.10070816e-02,
       2.19702145e-01, 1.00958512e-01, 4.99282556e-03, 8.79379728e-02,
       2.20666385e-02, 1.53939653e-01, 1.35693687e-02, 3.51858323e-02,
       1.77830344e-03, 9.08322972e-01, 9.80602303e-02, 2.63906937e-01,
      